lista = [18,10,60,38,50]
lista.append(10.5)
lista.append(20.5)
lista.append(30.5)
lista.append(40.5)
lista.append(50.5)
lista.pop()
lista.pop()
print(len(lista))
lista_ordenada = sorted(lista)
print(lista_ordenada)
print(max(lista))
print(min(lista))
lista_decrescente = sorted(lista, reverse=True)
print(lista_decrescente)
print(sum(lista))
media = sum(lista) / len(lista)
print(media)
lista.insert(0, (5))
lista.insert(1, (8))
print(lista)
for item in lista:
    print(item)
